{
  "_id": ObjectId,
  "model_name": "stock_signal_model_v1",
  "features": ["rsi", "macd", "ma_20", "bb_upper", "obv", ...],
  "target": "signal",                 // e.g., Buy, Hold, Sell (Classification)
  "algorithm": "XGBoostClassifier",  // বা অন্য কোন (RandomForest, LSTM ইত্যাদি)
  "train_start": "2024-01-01",
  "train_end": "2025-05-10",
  "accuracy": 0.873,
  "f1_score": 0.86,
  "recall": 0.84,
  "precision": 0.87,
  "confusion_matrix": [[50, 5, 2], [4, 45, 6], [3, 2, 48]],
  "date_trained": ISODate("2025-05-12T10:00:00Z")
}
